include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

.default-tags:
  tags: [ruby-2.7]

.postgres:
  tags:
    - ruby-2.7
    - postgres

.bundle: &bundle
  - bundle config set --local without development
  - bundle install -j $(sysctl -n hw.ncpu)

.yarn: &yarn
  - yarn install --pure-lockfile

.copy_master_key: &copy_master_key
  - cp $RAILS_CREDENTIALS_MASTER_KEY config/master.key

.production_env: &production_env
  name: production
  url: https://www.theater-kaisersesch.de

stages:
  - test
  - deploy
  - post-deploy

variables:
  RAILS_ENV: test
  NODE_ENV: test
  RUBOCOP_CACHE_ROOT: .cache/rubocop

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules
    - .cache
    - public/assets

rubocop:
  extends: .default-tags
  except:
    - schedules
  before_script:
    - *bundle
  script:
    - rubocop

standardjs:
  tags:
    - yarn
  except:
    - schedules
  before_script:
    - *yarn
  script:
    - yarn run standard

specs:
  extends: .postgres
  except:
    - schedules
  before_script:
    - *bundle
    - *copy_master_key
  script:
    - rails db:drop db:create db:structure:load
    - rails assets:precompile
    - rspec
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID"
    expose_as: 'SimpleCov report'
    paths:
      - 'coverage/'
    expire_in: 1 week

bundler audit:
  extends: .default-tags
  script:
    - gem install bundler-audit
    - bundle audit check --update

yarn audit:
  tags:
    - yarn
  before_script:
    - *yarn
  script:
    - npx audit-ci --high

deploy:
  extends: .default-tags
  except:
    - schedules
  stage: deploy
  before_script:
    - *bundle
  script:
    - ssh_wrap cap production deploy
  environment:
    <<: *production_env
  only:
    refs:
      - production

run one off task:
  extends: .default-tags
  except:
    - schedules
  stage: post-deploy
  before_script:
    - *bundle
  script:
    - ssh_wrap cap production one_off:run
  environment:
    <<: *production_env
  only:
    refs:
      - production
  when: manual
