.default-tags:
  tags: [ruby-2.6]

.postgres:
  tags:
    - ruby-2.6
    - postgres

.bundle: &bundle
  - bundle install -j $(sysctl -n hw.ncpu)

.copy_master_key: &copy_master_key
  - cp $RAILS_CREDENTIALS_MASTER_KEY config/master.key

variables:
  RAILS_ENV: test

rubocop:
  extends: .default-tags
  except:
    - schedules
  before_script:
    - *bundle
  script:
    - rubocop
  allow_failure: true

specs:
  extends: .postgres
  except:
    - schedules
  before_script:
    - *bundle
    - *copy_master_key
  script:
    - rails db:drop db:create db:structure:load
    - rails test
    - spring stop

audit:
  extends: .default-tags
  script:
    - gem install bundler-audit
    - bundle audit check --update

deploy:
  extends: .default-tags
  except:
    - schedules
  stage: deploy
  before_script:
    - *bundle
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - cap production deploy
    # needs to be run here (not in after_script) or the job will get stuck
    - ssh-agent -k
  environment:
    name: production
    url: https://www.theater-kaisersesch.de
  only:
    refs:
      - master
  when: manual
