variables:
  RAILS_ENV: test

before_script:
  - ruby -v
  - sudo pkg install -y v8 mysql57-client
  - bundle install -j $(sysctl -n hw.ncpu)
  - cp $RAILS_CREDENTIALS_MASTER_KEY config/master.key

rubocop:
  script:
    - gem install rubocop
    - rubocop
  allow_failure: true

specs:
  script:
    - rails db:drop db:create db:schema:load
    - rails test
    - spring stop

audit:
  script:
    - gem install bundler-audit
    - bundler-audit

deploy:
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - cap production deploy
    # needs to be run here (not in after_script) or the job will get stuck
    - ssh-agent -k
  environment:
    name: production
    url: https://www.theater-kaisersesch.de
  when: manual
