variables:
  RAILS_ENV: test

before_script:
  - ruby -v
  - sudo pkg install -y v8 mysql57-client
  # Install dependencies into ./vendor/ruby
  - bundle install -j $(sysctl -n hw.ncpu)

rubocop:
  script:
    - gem install rubocop
    - rubocop
  allow_failure: true

specs:
  script:
    - rails db:drop db:create db:schema:load
    - rails test
  allow_failure: true

audit:
  script:
    - gem install bundler-audit
    - bundler-audit

deploy:
  stage: deploy
  script: cap production deploy
  when: manual
