workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - when: always

.except_schedules:
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: always

.production:
  environment:
    name: production
    url: https://www.theater-kaisersesch.de
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
      when: manual

.default-tags:
  tags: [ruby-2.7]

.postgres:
  tags:
    - ruby-2.7
    - postgres

.bundle: &bundle
  - bundle config set --local without development
  - bundle install -j $(sysctl -n hw.ncpu)

.yarn: &yarn
  - yarn install --pure-lockfile

.copy_master_key: &copy_master_key
  - cp $RAILS_CREDENTIALS_MASTER_KEY config/master.key

stages:
  - test
  - deploy
  - post-deploy

variables:
  RAILS_ENV: test
  NODE_ENV: test
  RUBOCOP_CACHE_ROOT: .cache/rubocop

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules
    - .cache
    - public/assets

rubocop:
  extends:
    - .except_schedules
    - .default-tags
  before_script:
    - *bundle
  script:
    - rubocop

standardjs:
  extends: .except_schedules
  tags:
    - yarn
  before_script:
    - *yarn
  script:
    - yarn run standard

specs:
  extends:
    - .except_schedules
    - .postgres
  before_script:
    - *bundle
    - *copy_master_key
  script:
    - rails db:drop db:create db:schema:load
    - rails assets:precompile
    - rspec
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID"
    expose_as: 'SimpleCov report'
    paths:
      - 'coverage/'
    expire_in: 1 week

bundler audit:
  extends: .default-tags
  script:
    - gem install bundler-audit
    - bundle audit check --update

yarn audit:
  tags:
    - yarn
  before_script:
    - *yarn
  script:
    - npx audit-ci --high
  allow_failure: true

deploy:
  extends:
    - .production
    - .default-tags
  stage: deploy
  before_script:
    - *bundle
  script:
    - ssh_wrap cap production deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
      when: on_success

run one off task:
  extends:
    - .production
    - .default-tags
  stage: post-deploy
  before_script:
    - *bundle
  script:
    - ssh_wrap cap production one_off:run
