require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
  - 'bin/*'
  - 'db/migrate/*'
  - 'node_modules/**/*'

Layout/LineLength:
  Max: 80

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'
    - 'spec/**/*.rb'
    - 'lib/tasks/*.rake'
    - 'app/views/**/*.jbuilder'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/ParameterLists:
  CountKeywordArgs: false

Rails/ApplicationRecord:
  Exclude:
    - lib/passbook/models/**/*.rb

Rails/DynamicFindBy:
  Whitelist:
    - find_by_email

# disable this because we mostly use native enums in Postgres
Rails/EnumHash:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/RakeEnvironment:
  Exclude:
    - lib/capistrano/tasks/**/*.rake

Rails/SkipsModelValidations:
  Whitelist: ['touch']

Style/Documentation:
  Enabled: false
