require: rubocop-rails

AllCops:
  Exclude:
  - 'bin/*'
  - 'db/migrate/*'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'
    - 'spec/**/*.rb'
    - 'lib/tasks/*.rake'
    - 'app/views/**/*.jbuilder'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/ParameterLists:
  CountKeywordArgs: false

# disable this because we mostly use native enums in Postgres
Rails/EnumHash:
  Enabled: false

Rails/SkipsModelValidations:
  Whitelist: ['touch']

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - 'config/puma/*.rb'
