require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
  - 'bin/*'
  - 'node_modules/**/*'

Layout/LineLength:
  Max: 80
  Exclude:
    - db/migrate/*.rb

Lint/EmptyBlock:
  Exclude:
    - lib/tasks/one_off.rake

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'db/seeds.rb'
    - 'config/**/*.rb'
    - 'spec/**/*.rb'
    - 'lib/tasks/*.rake'
    - 'app/views/**/*.jbuilder'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 25
  Exclude:
    - db/migrate/*.rb

Metrics/ParameterLists:
  CountKeywordArgs: false

Rails/ApplicationRecord:
  Exclude:
    - lib/passbook/models/**/*.rb

Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_email

# disable this because we mostly use native enums in Postgres
Rails/EnumHash:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/RakeEnvironment:
  Exclude:
    - lib/capistrano/tasks/**/*.rake

Rails/SkipsModelValidations:
  AllowedMethods: ['touch']

Style/Documentation:
  Enabled: false
