require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
  - 'bin/*'
  - 'node_modules/**/*'
  - 'vendor/**/*'

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - lib/tasks/one_off.rake

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'db/**/*.rb'
    - 'config/**/*.rb'
    - 'spec/**/*.rb'
    - 'lib/tasks/*.rake'
    - 'app/views/**/*.jbuilder'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 25
  Exclude:
    - db/migrate/*.rb

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Metrics/ParameterLists:
  CountKeywordArgs: false

Rails/ApplicationRecord:
  Exclude:
    - lib/passbook/models/**/*.rb

Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_email

# disable this because we mostly use native enums in Postgres
Rails/EnumHash:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/RakeEnvironment:
  Exclude:
    - lib/capistrano/tasks/**/*.rake

Rails/SkipsModelValidations:
  AllowedMethods: ['touch']
  Exclude:
    - 'db/migrate/*.rb'

Rails/ThreeStateBooleanColumn:
  Exclude:
    - 'db/migrate/201*.rb'

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/Documentation:
  Enabled: false
