AllCops:
  TargetRubyVersion: 2.5
  Exclude:
  - 'bin/*'
  - 'db/migrate/*'
  - 'db/schema.rb'

Rails:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'
    - 'spec/**/*.rb'
    - 'lib/tasks/*.rake'
    - 'app/views/**/*.jbuilder'

Metrics/MethodLength:
  Max: 25

Rails/SkipsModelValidations:
  Whitelist: ['touch']

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - 'config/puma/*.rb'
