development:
  secret_token:
  url_options:
    host: ""
    protocol: http
  smtp:
    address: ""
    user_name: ""
    password: ""
    authentication: ""
  imagemagick_path: /opt/ImageMagick/bin/
  passbook:
    wwdr_ca_path: /usr/local/etc/ssl/AppleWWDRCA.cer
    developer_cert_path:
      "pass.de.theater-kaisersesch.FasT": "/usr/local/etc/ssl/pass.de.theater-kaisersesch.FasT.p12"
  ticket_barcode_base_url: ""
production:
  secret_token:
  url_options:
    host: www.theater-kaisersesch.de
    protocol: https
  passbook:
    wwdr_ca_path: /etc/ssl/chain/AppleWWDRCA.cer
    developer_cert_path:
      "pass.de.theater-kaisersesch.FasT": "/etc/ssl/private/pass.de.theater-kaisersesch.FasT.p12"
  ticket_barcode_base_url: "https://a0s.de/"
