development:
  secret_token:
  host: "fast.albisigns"
  imagemagick_path: "/opt/ImageMagick/bin/"
  passbook:
    wwdr_ca_path: "/usr/local/etc/ssl/AppleWWDRCA.cer"
    developer_cert_path: "/usr/local/etc/ssl/pass.de.theater-kaisersesch.FasT.p12"
production:
  secret_token:
  host: "www.theater-kaisersesch.de"
  passbook:
    wwdr_ca_path: "/etc/ssl/chain/AppleWWDRCA.cer"
    developer_cert_path: "/etc/ssl/private/pass.de.theater-kaisersesch.FasT.p12"