default: &default
  adapter: postgresql
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: fast_development
  user: postgres

test:
  <<: *default
  host: localhost
  database: fast_test
  username: postgres

production:
  <<: *default
  host: 'fd00::9'
  database: fast_production
  username: fast_production
  password: '<%= Rails.application.credentials.database[:password] %>'
