action_mailer:
  defaults:
    from: TheaterKultur Kaisersesch <noreply@theater-kaisersesch.de>
    reply_to: TheaterKultur Kaisersesch <info@theater-kaisersesch.de>
  mail_to_in_development:

contact_messages:
  mail_to: info@theater-kaisersesch.de

members:
  default_membership_fee: 12
  membership_renewal_after_months: 12
  membership_fee_debit_submission_email: albrecht@oster.online

newsletters:
  review_email: albrecht@oster.online
  review_subject: Newsletter ready for review

apns:
  team_id: V48L6BF6M3
  topics:
    stats: 'de.theater-kaisersesch.stats'

passbook:
  destination_path: '<%= File.join(Rails.public_path, %w[system passbook]) %>'
  wwdr_ca_path: '/usr/local/etc/ssl/chain/AppleWWDRCA.cer'
  models:
    - name: ticketing/ticket
      template: ticket
      pass_type_id: pass.de.theater-kaisersesch.FasT
      certificate_path: /usr/local/etc/ssl/private/pass.de.theater-kaisersesch.FasT.p12

sentry:
  enabled: false

shared_email_accounts:
  redirect_url: https://mail.theater-kaisersesch.de/?_task=login&_action=login

hide_it_recht_content: false

covid19:
  presence_tracing_email: true

tse:
  enabled: false
  host: tse.a0s.de
  port: 10001
