action_mailer:
  defaults:
    from: Freilichtbühne am schiefen Turm <noreply@theater-kaisersesch.de>
    reply_to: Freilichtbühne am schiefen Turm <info@theater-kaisersesch.de>
  mail_to_in_development: albo@a0s.de

contact_messages:
  mail_to: info@theater-kaisersesch.de

apns:
  team_id: V48L6BF6M3
  topics:
    stats: 'de.theater-kaisersesch.stats'

passbook:
  path: '<%= File.join(%w[system passbook]) %>'
  full_path: '<%= File.join(Rails.public_path, %w[system passbook]) %>'
  wwdr_ca_path: '/usr/local/etc/ssl/chain/AppleWWDRCA.cer'
  developer_cert_path:
    pass.de.theater-kaisersesch.FasT: '/usr/local/etc/ssl/private/pass.de.theater-kaisersesch.FasT.p12'
