smtp:
  address: smtp.a0s.de
  port: 587
  user_name: '<%= Rails.application.credentials.smtp[:user_name] %>'
  password: '<%= Rails.application.credentials.smtp[:password] %>'
  authentication: plain

url_options:
  host: www.theater-kaisersesch.de
  protocol: https

secure_session_cookie?: true

ticket_barcode_base_url: 'https://a0s.de/!'

sentry:
  enabled: true
