smtp:
  address: localhost
  port: 1025

url_options:
  host: www.theater-kaisersesch.de
  protocol: https

ticket_barcode_base_url: 'https://a0s.de/!'

members:
  membership_renewal_after_months: 6
  membership_application_admin_notification_email: foo@sample.de

ebics:
  enabled: false
